// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-XHxb78YuvdMAthFTbgf4N_XQlZjHLOU',
    appId: '1:774895050810:web:25e2ed45783b8ab5cc9503',
    messagingSenderId: '774895050810',
    projectId: 'tulapid-dfaed',
    authDomain: 'tulapid-dfaed.firebaseapp.com',
    storageBucket: 'tulapid-dfaed.firebasestorage.app',
    measurementId: 'G-GNHTB9T942',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvKOYW5pCknJkFgZS6pYunee9BuL3Ftrg',
    appId: '1:774895050810:android:2da86c4d42f31cc6cc9503',
    messagingSenderId: '774895050810',
    projectId: 'tulapid-dfaed',
    storageBucket: 'tulapid-dfaed.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-XHxb78YuvdMAthFTbgf4N_XQlZjHLOU',
    appId: '1:774895050810:web:19660ecc824db51dcc9503',
    messagingSenderId: '774895050810',
    projectId: 'tulapid-dfaed',
    authDomain: 'tulapid-dfaed.firebaseapp.com',
    storageBucket: 'tulapid-dfaed.firebasestorage.app',
    measurementId: 'G-S65PYW2DB8',
  );
}
